# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gms/progs++/vecplot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gms/progs++/vecplot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gms/progs++/vecplot/CMakeFiles /home/gms/progs++/vecplot//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gms/progs++/vecplot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named MGeomerty

# Build rule for target.
MGeomerty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MGeomerty
.PHONY : MGeomerty

# fast build rule for target.
MGeomerty/fast:
	$(MAKE) $(MAKESILENT) -f src/MGeomerty/CMakeFiles/MGeomerty.dir/build.make src/MGeomerty/CMakeFiles/MGeomerty.dir/build
.PHONY : MGeomerty/fast

#=============================================================================
# Target rules for targets named AbstractGL

# Build rule for target.
AbstractGL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AbstractGL
.PHONY : AbstractGL

# fast build rule for target.
AbstractGL/fast:
	$(MAKE) $(MAKESILENT) -f src/AbstractGL/CMakeFiles/AbstractGL.dir/build.make src/AbstractGL/CMakeFiles/AbstractGL.dir/build
.PHONY : AbstractGL/fast

src/Application.o: src/Application.cpp.o
.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i
.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s
.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/CoordinateSystem.o: src/CoordinateSystem.cpp.o
.PHONY : src/CoordinateSystem.o

# target to build an object file
src/CoordinateSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/CoordinateSystem.cpp.o
.PHONY : src/CoordinateSystem.cpp.o

src/CoordinateSystem.i: src/CoordinateSystem.cpp.i
.PHONY : src/CoordinateSystem.i

# target to preprocess a source file
src/CoordinateSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/CoordinateSystem.cpp.i
.PHONY : src/CoordinateSystem.cpp.i

src/CoordinateSystem.s: src/CoordinateSystem.cpp.s
.PHONY : src/CoordinateSystem.s

# target to generate assembly for a file
src/CoordinateSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/CoordinateSystem.cpp.s
.PHONY : src/CoordinateSystem.cpp.s

src/Raycaster.o: src/Raycaster.cpp.o
.PHONY : src/Raycaster.o

# target to build an object file
src/Raycaster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Raycaster.cpp.o
.PHONY : src/Raycaster.cpp.o

src/Raycaster.i: src/Raycaster.cpp.i
.PHONY : src/Raycaster.i

# target to preprocess a source file
src/Raycaster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Raycaster.cpp.i
.PHONY : src/Raycaster.cpp.i

src/Raycaster.s: src/Raycaster.cpp.s
.PHONY : src/Raycaster.s

# target to generate assembly for a file
src/Raycaster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Raycaster.cpp.s
.PHONY : src/Raycaster.cpp.s

src/VectorPlot.o: src/VectorPlot.cpp.o
.PHONY : src/VectorPlot.o

# target to build an object file
src/VectorPlot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/VectorPlot.cpp.o
.PHONY : src/VectorPlot.cpp.o

src/VectorPlot.i: src/VectorPlot.cpp.i
.PHONY : src/VectorPlot.i

# target to preprocess a source file
src/VectorPlot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/VectorPlot.cpp.i
.PHONY : src/VectorPlot.cpp.i

src/VectorPlot.s: src/VectorPlot.cpp.s
.PHONY : src/VectorPlot.s

# target to generate assembly for a file
src/VectorPlot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/VectorPlot.cpp.s
.PHONY : src/VectorPlot.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AbstractGL"
	@echo "... MGeomerty"
	@echo "... main"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/CoordinateSystem.o"
	@echo "... src/CoordinateSystem.i"
	@echo "... src/CoordinateSystem.s"
	@echo "... src/Raycaster.o"
	@echo "... src/Raycaster.i"
	@echo "... src/Raycaster.s"
	@echo "... src/VectorPlot.o"
	@echo "... src/VectorPlot.i"
	@echo "... src/VectorPlot.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

